### PR TITLE
[YT-CC-1217] credits section, support license key from NR add-on and display name

### PR DESCRIPTION
**Pull request by mikong**
Description of your patch
-------------

The update adds two new attributes:

* `default['newrelic_infra']['use_newrelic_addon']` - set to `true` to indicate that you want to use the license key from the New Relic add-on. When using this, there's no need to specify the license key with `default['newrelic_infra']['license_key']`.
* `default['newrelic_infra']['display_name']` - sets the `display_name` New Relic Infra configuration setting (see https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/configuration/configure-infrastructure-agent).

The README has been updated to describe these new attributes, and a Credits section was also added.

Recommended Release Notes
-------------

New Relic Infrastructure custom chef recipe adds new attributes to support using license key from New Relic add-on, and a custom display name for the hosts.

Estimated risk
-------------

Low - only affects customers who enable custom-newrelic_infra recipe.

Components involved
-------------

newrelic-infra

Description of testing done
-------------

Tested on a simple cluster: one app master, one db master.

The following cases were tested for the attribute `use_newrelic_addon`:

* Don't set `use_newrelic_addon`, /etc/newrelic-infra.yml contains license key set in attributes.rb
* Set `use_newrelic_addon` to `true`:
  * NR add-on is not activated on the environment. The /etc/newrelic-infra.yml contains a blank license key, even if you set the `license_key` attribute.
  * NR add-on is activated on the environment. The /etc/newrelic-infra.yml contains the license key from the NR account of the NR add-on.

Test cases for `display_name`:

* Don't set `display_name`. The /etc/newrelic-infra.yml should not have a `display_name` configuration.
* Set `dispaly_name` to a hardcoded value. The value must show in /etc/newrelic-infra.yml.
* Set `display_name` to dynamic value, `"#{node['dna']['environment']['name']}-#{node['dna']['instance_role']}"`. The /etc/newrelic-infra.yml must contain the display_name with a value that's a concatenation of the environment name and the instance role.

QA Instructions
-------------

TODO

### CODE REVIEW

**Comment by mikong** [comment]
@jegasega, good point. I'll update my PR soon to declare the dependency.

**Comment by radamanthus** [comment]
LGTM

**Comment by jegasega** [comment]
LGTM

**Comment by jegasega** [comment]
LGTM

**Pull request merged**
