### PR TITLE
Upgrade to Passenger 5.1.4

### PR DESCRIPTION
**Pull request by radamanthus**
NOTE: This PR is ready but while we're investigating CC-1174 (passenger tmp directories not being cleaned up) we will not yet include this in the next release. We don't want to change too many variables.

## Description of your patch

Upgrades Passenger to 5.1.4

## Recommended Release Notes

Upgrades Passenger to 5.1.4

## Estimated risk

Low. 

## Components involved

Passenger 5 main recipe

## Description of testing done

See QA instructions

## QA Instructions

Test on configuration A

1. New environment scenario
Boot a new environment under the QA stack
Verify that there are no chef errors
Verify that Passenger 5.1.4 is running: `passenger -v`
Deploy. Verify that the web application works without errors.

2. Upgrade scenario
Boot latest stable-v5 stack
Upgrade to the QA stack
Verify that there are no chef errors
Verify that Passenger 5.1.4 is running: `passenger -v`
Deploy. Verify that the web application works without errors.

### CODE REVIEW

**Comment by radamanthus** [comment]
Review the recipe and see if `/usr/share/elasticsearch/elasticsearch.in.sh` can also be moved to somewhere under `/opt`.

https://github.com/engineyard/ey-cookbooks-stable-v5/blob/1eddd7e70cbdb911d0e45f415eafd7de63f03437/cookbooks/elasticsearch/recipes/install.rb#L123-L130

**Comment by dvalfre** [comment]
@radamanthus your previous comment seems to be for PR #204 :wink:

**Comment by radamanthus** [comment]
We don't need to do this unless we see issues with 5.0.29, or customers ask for 5.1.x.

A customer can install Passenger 5.1.x by creating a passenger5 recipe that overrides https://github.com/engineyard/ey-cookbooks-stable-v5/blob/next-release/cookbooks/passenger5/attributes/passenger5.rb. The recipe can be as simple as:

```
- passenger5
  +- attributes
    +- passenger5.rb
```

with the `attributes/passenger5.rb` file containing the desired version. What is more important is we document this approach and communicate to customers that they can override the Passenger version this way.

**Comment by radamanthus** [comment]
The method for overriding the Passenger version is documented here: https://github.com/engineyard/ey-cookbooks-stable-v5/wiki/Customizing-Your-Environment-Using-Overlay-Chef-Recipes

**Pull request closed without merging**
