### PR TITLE
[EYPP-165] Add support for environment variables managed in cloud

### PR DESCRIPTION
**Pull request by rzaharenkov**
## Description of your patch

Created a new recipe (env_vars::cloud) as part of existing cookbook (env_vars). The purpose of the recipe is to generate a new file `env.cloud` in the `shared/config` directory.

Also modified a couple of recipes in order to source new generated file to the application servers (in the same way like it's done for `env.custom` file).

## Recommended Release Notes

* Added a new recipe that pulls environment variables configured on the cloud dashboard and injects it to the applications.

## Estimated risk

Low

### New recipe:
`cookbooks/env_vars/recipes/cloud.rb`

### An entry point for the new recipe:
`cookbooks/ey-application/recipes/create.rb`

### Updated config templates for the application servers:
`cookbooks/node/templates/default/app_control.sh.erb`
`cookbooks/passenger5/templates/default/app_control.erb`
`cookbooks/php/templates/default/fpm-pool.conf.erb`
`cookbooks/pm2/templates/default/app_control.sh.erb`
`cookbooks/puma/templates/default/app_control.erb`
`cookbooks/sidekiq/files/default/sidekiq`
`cookbooks/unicorn/templates/default/unicorn.initd.sh.erb`

### Apply this cookbook to existing instance
Upgrade existing instance to the new stack. File `dna.json` doesn't contains any variables configured so an empty file is generated and nothing changed. Here a stack that includes my changes: [rz_test-0.1](https://stacks.engineyard.com/admin/stacks/rz_test-0.1)

### Apply this cookbook to updated instance
1. Deploy a [custom branch of AWSM](https://github.com/engineyard/awsm/tree/rz-env-dna) to some of staging environment. I've used [mission](https://mission.engineyard.com/) for the testing.

2. Configure some environment variables on the cloud panel (it requires to turn on the feature in early access tab). Variables used for test are [here](https://mission.engineyard.com/app_deployments/264/environment/environment_variables)

3. Apply instance changes in order to populate variables to `dna.json`

4. Inspect a list of variables on the application side: [variables in the app](http://ec2-23-23-125-26.compute-1.amazonaws.com/environment)

## QA Instructions

Follow testing instructions above.

### CODE REVIEW

**Comment by radamanthus** [comment]
@rzaharenkov mind updating the PR description to follow the format below? Please see closed PRs for examples. Thanks!

```
## Description of your patch

## Recommended Release Notes

## Estimated risk

## Components involved

## Description of testing done

## QA Instructions
```

**Comment by rzaharenkov** [comment]
@radamanthus, updated

**Comment by rzaharenkov** [comment]
btw, when I build a release of my development stack it fails tests for some reason: https://dredd.engineyard.com/suites/f961b8ab-f677-4d2e-bf06-033d4b9022b4. As I can see test suite itself fails on this particular line: https://github.com/engineyard/dredd/blob/master/scenarios/solo.rb#L41. But I have no idea how to debug/test it. Although Dredd build are failing it releases stack successfully and this stack works fine.

**Comment by rzaharenkov** [comment]
Please ignore my last comment. Fixed the problem with Dredd. There was a problem in my code, fixed now: https://dredd.engineyard.com/suites/0c20b1e6-8f4d-47db-b4a5-839b9fd7f19d

**Comment by radamanthus** [comment]
LGTM

**Comment by radamanthus** [comment]
Thanks for the hard work on this! Code looks good and we should be able to include this in the PRs to be tested for the release after v5-3.0.31

One small thing I'd request in the future is to have the whitespace cleanup in a separate commit. I know, it violates our squash commits rule, but doing it this way makes it easier for the reviewer to see if he should be looking for cleanup-related changes or actual code changes.

**Comment by rzaharenkov** [comment]
Thanks @radamanthus! Your comment is 100% valid. I will try to do as separate commit next time. The problem is sublime did it unintendedly when I saved that files.

I am going to merge it. Do you have an idea when it will be released?

**Comment by JBRC-ph** [comment]
@rzaharenkov Thanks! This is supposed to go into the next release. But a new urgent update is requested by Distro - I'll get that update out into a release by next week, and then this goes into the release after that.

**Comment by radamanthus** [comment]
@rzaharenkov Thanks! This is supposed to go into the next release. But a new urgent update is requested by Distro - I'll get that update out into a release by next week, and then this goes into the release after that.

Also next time please do not merge code changes directly into next-release. Let the release management process (@dbeckstead and me) do the merging.

**Comment by rzaharenkov** [comment]
Ah, sorry, I just thought it stuck for some reason. Has been approved 3 weeks ago and don't megred yet.

**Pull request merged**
